# Generated by Django 3.2.13 on 2022-06-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='image', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
